services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
    networks:
      - acmutd-api
networks:
  acmutd-api:
