services:
  app:
    build:
      context: .
      dockerfile: api.Dockerfile
      target: prod
    restart: unless-stopped
    ports:
      - ${PORT}:${PORT}
    environment:
      PORT: ${PORT}
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
    networks:
      - acmutd-api
  scraper:
    build:
      context: .
      dockerfile: scraper.Dockerfile
    environment:
      OUTPUT_DIR: /app/output
      FIREBASE_CONFIG: ${FIREBASE_CONFIG}
      NETID: ${NETID}
      PASSWORD: ${PASSWORD}
      CLASS_TERMS: ${CLASS_TERMS}
    volumes:
      - ./output:/app/output
    networks:
      - acmutd-api
networks:
  acmutd-api:
